Add publish dry-run logic

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -161,4 +161,19 @@ publish-on-tag:
     # version of the package
     - |
       PACKAGE_VERSION="v$(poetry version -s)"
-      echo "PACKAGE_VERSION: ${PACKAGE_VERSION}"
+      if [[ "${CI_COMMIT_TAG}" != "${PACKAGE_VERSION}" ]]
+      then
+        echo "ERROR: Git tag reference and package version are NOT synonymous."
+        echo "       Package version: ${PACKAGE_VERSION}"
+        echo "       Git ref name   : ${CI_COMMIT_TAG}"
+        exit 1
+      fi
+    # Actually publish
+    - |
+      if [[ -z "${PYPI_PUBLISH_TOKEN}" ]]
+      then
+        echo "ERROR: Expected PYPI token variable was blank."
+        echo "       Did you forget to set the appropriate PYPI_PUBLISH_TOKEN secret?"
+        exit 1
+      fi
+    - poetry publish --build --dry-run
